name: tests

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install cover
      run: go get golang.org/x/tools/cmd/cover

    - name: Install goveralls
      run: go get -u github.com/mattn/goveralls

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Update Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
